version: '3'
services:
  database:
    container_name: dbdirectus_myid
    image: postgis/postgis:15-3.3
    # Required when running on platform other than amd64, like Apple M1/M2:
    # platform: linux/amd64
    ports:
      - 5102:5432
    volumes:
      - ./pgdata/database:/var/lib/postgresql/data
    networks:
      - directus
    environment:
      POSTGRES_USER: 'dawamr'
      POSTGRES_PASSWORD: '@Renewable22'
      POSTGRES_DB: 'cmsmyid'
    restart: always
  # cache:
      #container_name: directus-cache
      #image: redis:6
      #networks:
      #  - directus
      #restart: always
  directus:
    container_name: paneldirectus_myid
    image: directus/directus:10.7.2
    ports:
      - 5101:8055
    volumes:
      - ./directusdata/uploads:/directus/uploads
      - ./directusdata/extensions:/directus/extensions  
    networks:
      - directus
    restart: always
    depends_on:
      - database
    environment:
      KEY: 'myAppKey'
      SECRET: '1234567890-0987654321'
      # ... (your other environment configurations remain the same)
      DB_CLIENT: 'pg'
      DB_HOST: 'database'  # Use the service name of the PostgreSQL container in the same network
      DB_PORT: '5432'
      DB_DATABASE: 'cmsmyid'
      DB_USER: 'dawamr'
      DB_PASSWORD: '@Renewable22'
      # ... (your other environment configurations remain the same)
      CACHE_ENABLED: 'false'
      CACHE_STORE: 'redis'
      CACHE_TTL: '3m'
      
      REDIS: 'redis://default:Renewable22@175.106.9.60:6379/7'
      
      RATE_LIMITER_ENABLED: 'false'
      RATE_LIMITER_POINTS: '25'
      RATE_LIMITER_DURATION: '2'
      RATE_LIMITER_STORE: 'redis'
      
      RATE_LIMITER_GLOBAL_POINTS: '250'
      RATE_LIMITER_GLOBAL_DURATION: '5'
      
      WEBSOCKETS_ENABLED: 'true'

      #   EMAIL_SMTP_HOST: ''
      #   EMAIL_SMTP_PORT: ''
      #   EMAIL_SMTP_USER: ''
      #   EMAIL_SMTP_PASSWORD: ''
      #   EMAIL_SMTP_SECURE: ''

      ADMIN_EMAIL: 'id.dawamraja@gmail.com'
      ADMIN_PASSWORD: 'secret'

        # Make sure to set this in production
        # (see https://docs.directus.io/self-hosted/config-options#general)
        # PUBLIC_URL: 'https://dts.terretech.id'
      #entrypoint: sh -c 'su chown -R node:node /directus/uploads && chown -R node:node /directus/extensions && docker-entrypoint.sh'
networks:
  directus: